export interface IMicronutrient {
  id: number;
  cholesterol: number;
  fiber: number;
  sodium: number;
  water: number;
  vitaminA: number;
  vitaminB6: number;
  vitaminB12: number;
  vitaminC: number;
  vitaminD: number;
  vitaminE: number;
  vitaminK: number;
  calcium: number;
  iron: number;
  magnesium: number;
  phosphorus: number;
  potassium: number;
  zinc: number;
  copper: number;
  selenium: number;
  thiamin: number;
  riboflavin: number;
  niacin: number;
  pantothenicAcid: number;
  folateTotal: number;
  chloride: number;
  starch: number;
  lactose: number | null;
  alcohol: number | null;
  caffeine: number | null;
  sugars: number | null;
  fluoride: number | null;
  manganese: number | null;
  folicAcid: number | null;
  fattyAcidsTotalTrans: number | null;
  fattyAcidsTotalSaturated: number | null;
  fattyAcidsTotalMonounsaturated: number | null;
  fattyAcidsTotalPolyunsaturated: number | null;
}
